### PR TITLE
Keep lines and columns in tokens for error reporting

### PR DESCRIPTION
**Pull request by pstuifzand**
Count lines and columns and show these when errors occur in the reader.

### CODE REVIEW

**Comment by kode4food** [comment]
Heya @pstuifzand I noticed that this was in a draft form for a while, so went ahead and did it myself. Am about to push the change tonight. One question though, was there a reason for the `line:YY:XX` format that you used? Easier to parse? I opted to just go with a `(line YY, column XX)` format, but can change it if there's a reason to do otherwise.

**Comment by pstuifzand** [comment]
Thank you. No reason other than that I wanted both numbers in there.

**Comment by kode4food** [comment]
@pstuifzand Cool, so if you do a pull later tonight you should get something in the following format:

```
user [1]> 999 )
     [1]! encountered ')' with no open list (line 1, column 5)
```

**Comment by kode4food** [comment]
Covered by [67bc16f
](https://github.com/kode4food/ale/commit/67bc16f341bd44ba830ef26f14287a91faebbc14)

**Pull request closed without merging**
